### ISSUE TITLE
Cleanup of code generated from switch cases - remove dead code

### ISSUE THREAD

**Issue by peterz-dps** [insieme/insieme#101]
The translation of a switch statement often causes the code of multiple cases to end up within each single case - separated by break statements. The code behind each break actually is dead code and could be removed.

This should be easily solvable with a pattern matcher - however we must not forget to also look for labels after the break statement - in this case the code might not be dead after all.

Also note that the same arguments also holds for continue, return and throw. All of these are normally followed only by dead code.

**Comment by HerbertJordan** [comment]
Why focus on this special case? Why not implement a complete, general dead code elimination?

**Comment by philippgs** [comment]
Three remarks I'd like to raise:

1) @PeterTh already implemented a redundant code elimination some time ago, the ```SuperfluousCleanupExtension``` frontend extension - could/should both functionalities be common features of a single entity?

2) Should this be a frontend or a core utility? I guess for both dead and redundant code elimination, it might be useful in post-frontend stages, especially with components such as the PL potentially generating messy code.

3) Performance is to be considered. The redundant code elimination is currently based on a fixed point iteration and can take quite long for larger codes.

**Comment by HerbertJordan** [comment]
1) the frontend extension should use the resulting tool. We should not mix up several functionalities in one entity. Unix Philosophy: lots of specialized tools to combine.

2) i'd put it in the transformation module since it might require the analysis module as a foundation for the analysis; so it can be used by other transformations, transformation scripts, the frontend, or the backend;

3) Context-Insensitive, Path-Insensitive Dead-Code analysis on a program is a forward analysis that can be done in linear time (e.g. by considering it a DFA).

**Comment by PeterTh** [comment]
I did this for all common cases, very simply, and with basically 0 performance overhead, directly in the new frontend switch/case handling.
