### ISSUE TITLE
Insieme - build failure

### ISSUE THREAD

**Issue by ncos** [insieme/insieme#115]
Hi,

I am striving to build Insieme on Fedora 20, but no matter what I am trying to do I am drowning in errors. Here is a short log of what I have encountered - maybe you could resolve some of my issues.
1) I started the README tutorial on build process, but barvinok lib did not want to get itself to install - it emitted  
```
error: pathspec 'scripts/barvinok-0.35/polylib' did not match any file(s) known to git.
Did you forget to 'git add'?
checking which polylib to use... system
checking polylib/polylibgmp.h usability... no
checking polylib/polylibgmp.h presence... no
checking for polylib/polylibgmp.h... no
configure: error: Need PolyLib
```
Apparently, barvinok needs polylib, so (as it says on barvinok's website) you should execute *git submodule init* and *git submodule update* after downloading their repo. Insieme's build script operates with a copy of their repo and does not put polylib where it belongs (at list on my setup). 
Yet I managed to install barvinok manually and, thus, have no problems with it now.

2) Launching cmake (with setting up LD_LIBRARY_PATH as described in the tutorial) also led to some difficulties: the script failed to locate clang, llvm, cloog and several other libs. I had to manually set both CLANG_ROOT and LLVM_ROOT (strange, as the first should be by default equal to the latter according to the 'FindLLVM.cmake'). Even more confusing - I had to set BISON_ROOT *and* BISON_EXECUTABLE to make *cmake* find bison executable. I have also set other smth_ROOT variables which cmake complained about. Finally, *cmake* has generated me the makefile!

3) There is apparently a problem with boost version detection - when manually specifying boost 1.50 location everything seems fine (apart from gtest), but when not specifying it tries to use the system 1.54 and fails with lots of errors.

4) Upon building, make seemingly tries to download gtest, but I am working on a remote server with limited internet connection, so I tried to execute *scripts/gtest_install.sh* (successfully) and put the resulting folder in LD_LIBRARY_PATH. Regenerating the whole project did not result in anything. Can I somehow specify that I do not need to download gtest?

Well, the only real hindrance for me is 'gtest' (4) (Other faults just FYI). Any suggestion regarding that matter would be really appreciated!

Thank you in advance!

**Comment by philippgs** [comment]
Thanks for your detailed feedback!

As you already noticed, we are currently doing a major overhaul of Insieme, hence it is not very stable at the moment, right down to the build setup (which you still went through pretty far, well done!).

ad 1) thanks for reporting this. If you're right about the wrong extraction path, this should be an easy fix - I will have a look. The reason we cache all the sources is simply availability, as we already experienced numerous dead URLs for our external dependencies in the past.

ad 2) much more importantly than LD_LIBRARY_PATH: Did you also set INSIEME_LIBS_HOME? LD_LIBRARY_PATH is mainly required for locating stdlib and alike when using non-system compilers (such as our own installation of g++/gcc for example), and for hwloc (required by the Insieme runtime system). However, INSIEME_LIBS_HOME is basically required for everything, superseding any additional paths such as BOOST_ROOT, etc... (assuming they're to be found using the directory structure imposed by our installation scripts). If you install all external dependencies via our installation scripts, then INSIEME_LIBS_HOME and LD_LIBRARY_PATH are the only two env vars required.

ad 3) As our README says, we only test for compatibility with Boost 1.50. Relaxing our dependencies on exact versions and libraries in general is among our goals, but quite far down in the list of priorities, since we've got bigger fish to fry right now ;).

ad 4) Downloading gtest when executing make is expected behavior. According to their FAQ, gtest should always be built with the exact same compiler and version that is used to build the sources which depend on gtest - by lazily downloading and compiling only upon calling make, we ensure that indeed the same compiler is used. I see two possible workarounds for this: Try to change https://github.com/insieme/insieme/blob/f44fc926193f42cf72041e5e33332203e62b879a/code/cmake/add_unit_test.cmake#L21 to point to the path of your gtest installation. If that does not work, you could try to change the URLs at https://github.com/insieme/insieme/blob/f44fc926193f42cf72041e5e33332203e62b879a/scripts/gtest_external_project.cmake#L12 and https://github.com/insieme/insieme/blob/f44fc926193f42cf72041e5e33332203e62b879a/code/cmake/add_unit_test.cmake#L30 to point to a network location that works for you.

**Comment by ncos** [comment]
Thank you for your answer!

- You were totally right regarding INSIEME_LIBS_HOME. I have somehow missed it when I read the instructions. Sorry for that.

- I have also solved my problems with gtest by setting up a proper proxy (that turned out to be easier than I thought). So, I was able to successfully build the compiler and run the tests.

Again, thank you for your help

**Comment by philippgs** [comment]
Glad to hear! In any case, you raised a valid point with gtest. We'll provide other solutions of obtaining gtest in the future so one doesn't necessarily need Internet access for compilation.
