### ISSUE TITLE
Semantic checks for composite member access with TagTypeReferences

### ISSUE THREAD

**Issue by PeterTh** [insieme/insieme#128]
`TagTypeReferences` are not correctly checked by the current semantic check. This is particularly crucial for field access in classes.

Currently, these can pass any arbitrary type literal, and this operation will be assumed to be correct.

**Comment by HerbertJordan** [comment]
The corresponding type check requires a re-build since it was originally implemented based on the assumption that no recursive type variable (now reference) may ever be visible in its free form. Now that we have expressions within types to model objects, this is no longer valid.

I started working on this.

**Comment by HerbertJordan** [comment]
The issue with the big number 128 has been fixed by f122cb6ee7f6236d664fcada03c766b00c08fea7
