### ISSUE TITLE
Infer IntTypeParam values for derived constructs and create specialized versions when necessary

### ISSUE THREAD

**Issue by peterz-dps** [insieme/insieme#21]
Transistioning from using literals to derived operations for certain constructs (i.e. vector operations) broke some unit tests. We recognized this when debugging the wrong results for the feature extraction. Also this may relate to the problems the CBA framework has with some constructs.

The problem is that IntTypeParam values aren't correctly inferred (or not at all?) for derived IR constructs. This causes the feature extraction to fail and simply count the default values for loops and so on.

Sample IR:
```
let add_vector = (vector<'res,#l> a, vector<'res,#l> b) -> vector<'res, #l> {
  vector<'res, #l> res;
  return res;
};

unit main() {
  vector<int<4>, 2> a;
  vector<int<4>, 2> b;
  add_vector(a, b);
}
```
The function add_vector will not be specialized for the actual parameter types causing the StringLiteral "#l" to end up in the analyzed IR.

We probably need to create a new pass which instantiates all these constructs according to their use before the analysis can take place. Also the macros used to identify derived constructs (isXXX in lang base as well as extensions) need to be adapted to recognize the generic as well as the specialized version in IR and treat them equally.

**Comment by PeterTh** [comment]
This is awesome.

**Comment by HerbertJordan** [comment]
The feature-extractor is 'by design' a flow-insensitive, context-insensitive analysis. The requested task is therefore beyond its scope. In particular, as you suggested, no parameters are inferred -- ever. Not even attempted. 

The problem of tracing those values is a data-flow problem and need corresponding handling, which for the general case requires a bit more considerations.

I would not recommend to specialize those calls in the IR due to the issue of code blow-up and the problem that the reverse operation is next to impossible. Generalization once lost in the compilation process will not be re-gained.

If this kind of accuracy is required by the user, the analysis (in this case the feature extractor) should be equipped with the necessary techniques to deal with the generic IR. If this topic is picked up by somebody, i can provide some advice.

**Comment by PeterTh** [comment]
The specific issue we are solving (vector types) doesn't really lead to uncontrolled code blow-up, since at worst you'll have 3 or 4 actual instantiations of the types (e.g. width 2,4 and 8). I think it's very useful to have the capability of instantiating concrete types for such cases.

**Comment by HerbertJordan** [comment]
I still would, due to the problem regarding the re-generalization, limit the instantiation to the scope of the analysis, hence the feature extractor and not make it a compiler wide, generally applied idiom.

**Comment by PeterTh** [comment]
Yes, I agree. For now at least.

**Comment by PeterTh** [comment]
Done.
https://github.com/insieme/insieme/commit/acee4729049c58bb2427b2c46d82656eef089184

**Comment by HerbertJordan** [comment]
Is this a duplication of the function https://github.com/insieme/insieme/blob/master/code/core/include/insieme/core/transform/manipulation.h#L354 ?

**Comment by PeterTh** [comment]
I didn't know that function, but I think it's not a (direct) duplicate. This new instantiate() call works on any node type, and instantiates everything possible, recursively, to any call depth.

Perhaps it could internally use the existing instantiate functionality.

**Comment by peterz-dps** [comment]
This needs some more attention.
- The use of higher order functions isn't covered - neither are recoursive functions.
- Also we should compare this with the functionality offered by the code @HerbertJordan pointed out above and maybe merge/reuse common parts
