### ISSUE TITLE
Check Backend generation of multiple functions which are the exact same IR

### ISSUE THREAD

**Issue by PeterTh** [insieme/insieme#23]
There is the theoretical possibility of requiring multiple functions in the backend C code which map to the exact same IR code. Most likely, only one of these would actually be generated.

**Comment by HerbertJordan** [comment]
Not sure what this question is actually about ...

**Comment by PeterTh** [comment]
I remembered what this question was actually about!
https://github.com/insieme/insieme/commit/ae8103f32d43d5efdbe74d153cf763e9db4a5ed1

If you have two lambdas with the same code, and the are generated as WIs, the C code will not compile as one of them will not be generated.

**Comment by HerbertJordan** [comment]
I can check this out once I'm back.

**Comment by HerbertJordan** [comment]
The problem was caused by the enforced re-naming of functions implementing work items to a user-readable naming scheme. It was assumed that work item implementations are exclusive.

The fix is 54452c2 using a pointer to the implementation function instead of solely the function name to reference to implementations within the work item table. Thus, in the unlikely case of a shared implementation, the last rename step will be effective.
