### ISSUE TITLE
Environment variable based backend compiler selection

### ISSUE THREAD

**Issue by HerbertJordan** [insieme/insieme#28]
The compiler utilities in the utils -- and consequently all unit tests -- should a mechanism to influence the selection of a backend compiler (e.g. gcc-4.8, g++-4.9) based on environment variables CC and CXX.

At the moment, it utilizes a hard-coded compiler. Add support for obtaining the compiler to use form the mentioned environement variables, with a hard-coded fallback -- which ideally corresponds to the compiler utilized to compile the insieme compiler itself.

Any other ideas on how to steer the backend-compiler selection?

**Comment by philippgs** [comment]
One tiny issue to consider here are makefiles and such, which might contain something along the lines of `CXX=insiemecc`. To also support these cases I'd suggest allowing both environment variables **and** command line arguments to set the backend compiler(s), and give precedence to the latter.

Also, we might want to consider setting the hard-coded default to the system default `cc` instead of the compiler used to build Insieme (consider use cases such as GEMSCLAIM), however some of our systems will then default to gcc 4.4. ...

**Comment by HerbertJordan** [comment]
I just noticed that the CC environment variable is already supported ...

**Comment by philippgs** [comment]
Fixed in 94e3e662d861e8a6cd0a3a7d1f43e72537069344. The environment variables are called INSIEME_C_COMPILER and INSIEME_CXX_COMPILER respectively. If they are not set, the backend compiler setting defaults to gcc/g++.
