### ISSUE TITLE
Decide on representation of arrays in IR (single- and multi-dimensional, static and dynamic, heap and stack)

### ISSUE THREAD

**Issue by PeterTh** [insieme/insieme#42]
Generate exhaustive list of valid C cases for array (i) generation + allocation, and (ii) access.

**Comment by PeterTh** [comment]
@LuisAyuso @0ife @PeterTh

**Comment by HerbertJordan** [comment]
Ok ... i give it a shot (please extend as new things come up):

C r-value type | IR
----|----
`int a[15]` | `ref<vector<int<4>,15>> a = ref.var(vector<int<4>,15>>)`
`int a[12][15]` | `ref<vector<vector<int<4>,15>,12>> a = ref.var(...)`
`int a[20][12][15]` | `ref<vector<vector<vector<int<4>,15>,12>,20>> a = ref.var(...)`
`int*a` | `ptr<int<4>> a = ref.var(ref.null());`
`int(*a)[15]` | `ptr<vector<int<4>,15>> a = ref.var(ref.null())`
`int(*a)[12][15]` | `ptr<vector<vector<int<4>,15>,12>> a = ref.var(ref.null())`
`int(*a)[20][12][15]` | `ptr<vector<vector<vector<int<4>,15>,12>,20>> a = ref.var(ref.null())`
`int(*a)[]` | `ptr<array<int<4>,1>> a = ref.var(ref.null())`
`int(*a)[][15]` | `ptr<array<vector<int<4>,15>,1>> a = ref.var(ref.null())`
`int(*a)[][12][15]` | `ptr<array<vector<vector<int<4>,15>,12>,1>> a = ref.var(ref.null())`
`int a[s]` | `ref<array<int<4>,1>> a = ref.var(array.create(int<4>,vector.init([2])))`
`int a[s][s+1]` | `ref<array<int<4>,2>> a = ref.var(array.create(int<4>,vector.init([s,s+1])))`
`int a[s][s+1][s+2]` | `ref<array<int<4>,3>> a = ref.var(array.create(int<4>,vector.init([s,s+1,s+2])))`
`int(*a)[][s]` | `ref<array<int<4>,2>> a = ref.var(ref.null())`
`int(*a)[][s][s+1]` | `ref<array<int<4>,3>> a = ref.var(ref.null())`
`int(*a)[][s][s+1][s+2]` | `ref<array<int<4>,4>> a = ref.var(ref.null())`

where `ptr<X>` is either `ref<ref<X>>`, `ref<ref<array<X,1>>>` or any other encoding of a pointer (orthogonal issue).

In the examples I assume a generalized version of the `array.create_1D` and `array.create_ND` which is equivalent to the ND version. Except for the last three cases (those with the dynamically sized dimensions) the present constructs are sufficient.

**Comment by LuisAyuso** [comment]
I have being sleeping about it, and now I think that multidimensional arrays should be implemented in a coherent way with nested pointers, since usage of both is equivalent. 
My confusion comes from my lack of understanding of the backend, and the decisions taken there.

more important than the declaration of arrays (which is trivial), is the way you use them:

` decl`| `use` | `ir`
`int a[n][n];` | ` a [i][j]` | `??`
`int** a =  malloc (...) for each a: a[i] = malloc (...) ` | ` a [i][j]` | `??`

**Comment by LuisAyuso** [comment]
I have being sleeping about it, and now I think that multidimensional arrays should be implemented in a coherent way with nested pointers, since usage of both is equivalent.
My confusion comes from my lack of understanding of the backend, and the decisions taken there.

more important than the declaration of arrays (which is trivial), is the way you use them:

decl | use | ir
---- | ---- | ----
`int a[n][n];` | `a [i][j]` | `??`
`int** a = malloc (...); for each a: a[i] = malloc (...);` |` a [i][j]` | `??`
`int a[n][n];` | `a [i][j]` | `??`
`int** a = malloc (...); for each a: a[i] = malloc (...); `| `a [i]` | `??`

**Comment by 0ife** [comment]
RFC:

The whole point of having arrays and pointers versus only pointers is to make life easier, to be able to reason about the code. In that light we should make arrays as accessible as possible, especially for analysis. Hence I propose to have
* (in the IR) a **distinct array data type** (not related to pointers) where it is easy to see how many dimensions this space is comprised of, without traversing pointers to pointers... peeling off subscripts will not make our lifes easier (on the contrary)
* (in Insieme frontend) methods to parse the input language to the proper IR representation for arrays. The **first-time conversion** (source code to INSPIRE) [is dependent on the input language](https://en.wikipedia.org/wiki/Row-major_order), so it has to happen in the frontend: Remember that eg Fortran handles array indices complementary (column-major order) to C/C++ (row-major order).
* (in Insieme, perhaps core?) **methods to convert 1D/ND arrays to pointers** and vice versa. These conversion functions are not a priority, as it is deemed bad coding practice anyway to do pointer arithmetic, especially on arrays.

The functionality in INSPIRE should be designed in a way that it is possible to easily **extract subspaces from a space** (generate n-1 dimensional array of n-dimensional array by some selection criteria), or to **embed a space in a higher-dimensional space** (n-dimensional array to n+1 dimensional array). How this can be achieved is not clear to me, yet. Ideas? Comments? Proposals?

**Comment by LuisAyuso** [comment]
just to make it clear to me, do you mean to keep a ND_array and 1D_array type, where 1D_array?
Pointer and arrays are related no matter what we do, so I'm afraid whatever this turns to be needs to be coherent. 

I see two paths: The distinguished ND_array type with full suport or to drop it and use the nesting of types. Both have advantages and disadvantages:
- ND_ARRAY:  the use of this makes very easy to identify multidimensional arrays and play with them in the analysis, I see two disadvantages with this one, it will be very difficult in the frontend to identify this shape when using dynamic memory. And we need derived operators to extract subranges when the access is not just one element.
- Array<array< : Lately I find this more IR-friendly, the acces to elements or subranges is trivial, the translation is easy. I see two problems again: It aliases with non-array related pointers (for crazy C stuff) and it might require little magic in the backend to decide where to put it. (is it stack, heap, do I care?)

**Comment by HerbertJordan** [comment]
Sorry, had no time yesterday to contribute ... i will do so tonight.

For now I just figured out that runtime-sized arrays are only a C99 thing. C++ support is optional -- but GCC does, so I guess we have to do so too. It was suggested for C++14 but dropped -- and GCC apparently followed this step (https://gcc.gnu.org/projects/cxx1y.html).

The specification, by the way, is full of exceptions regarding pointers, references, captures, typedefs, ...
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3639.html

**Comment by HerbertJordan** [comment]
Much more details:
https://gcc.gnu.org/onlinedocs/gcc/Variable-Length.html

(i would add it to the previous message but the browser I'm forced to use is so old that the edit function is not working)

**Comment by HerbertJordan** [comment]
Please node the nice interaction between variable-sized arrays and alloca.

**Comment by HerbertJordan** [comment]
Another aspect probably to be considered: the upcoming / present Cilk_plus array notation.
https://www.cilkplus.org/tutorial-array-notation
However, at some point we have to ask how far we'd like to go.

**Comment by 0ife** [comment]
Just to mention the good writeup on Wikipedia reg [Variable-length Arrays (VLAs)](https://en.wikipedia.org/wiki/Variable-length_array) and the fact that C14 does not include them in the standard, but [C17 might again](http://stackoverflow.com/a/17318040). Anyway, we should make our minds up based upon our needs, not some standard.

**Comment by HerbertJordan** [comment]
It is pretty obvious that the troubles with those VLAs are caused by the mixture of values and types. Instances do not have a type describing their structure like any other C/C++ construct, but there structure is depending on some value of some linked variable. It is obviously a hack in the language that is just there because it is a nice feature that can easily be supported by compilers -- ignoring the ugly consequences regarding the language standard.

That said, it would actually be an awesome feature for many HPC codes using multi-dimensional arrays. Offering nice support for those would be definitely desirable -- we might just have to think about a more advanced type system capable of expressing such value dependencies nicely. As you said, we have to make up our minds.

**Comment by LuisAyuso** [comment]
Sorry, but, as usual, i don't follow you.

I don't think we need to change anything on the typing system, why do you think that? can you give us an example of what you have in mind? 

Dynamicaly sized arrays type can not be complete at compile time, but our 'array<'a, #n>' type is not does not contain the size, and the dimensions are known, always.

**Comment by HerbertJordan** [comment]
If in C99 you write
```C
int a[7][6][5];
```
you have an ordinary, statically sized array of type `int[7][6][5]` and if you access
```C
a[1][2][3]
```
then the compiler generates assembly code similar to
```C
*(%a + (1*6*5+2*5 + 3) * sizeof(int))
```
where %a is the address of the first element. The important thing is that you can retrieve the factors `6` and `5` from the type of `a`. That's why you can pass on `a` as a properly typed pointer to a function and still access it within those type-safe using the multi-dimensional subscripts. It also explains why the first dimension may be left empty when using heap-allocated arrays or passing them as an argument.

To the contrast, when you write
```C
int s1 = f(...);
int s2 = g(...);
int s3 = h(...);
int a[s1][s2][s3];
```
in C99 then `a` is a dynamically sized array with 3 dimensions. The access from above will be encoded by
```C
*(%a + (1*s2*s3+2*s3 + 3) * sizeof(int))
```
where %a is the base address of the local array `a`. Unlike for any other type in the C-family those offsets are not retrieved solely from the type of the accessed value (which I think is denoted by `int[*][*][*]`). The compiler needs to be aware of the memory locations s2 and s3 storing the actual offsets to be able to access elements at the right position. This is why such a dynamically sized array can not be passed on to any function (unless also passing on s2 and s3 and explicitly linking those parameters with the type) nor can you use such types in `typedef`s or references. Unlike any other C/C++ type the type information on its own does not cover the necessary details to decide how to apply access operations on corresponding values. Should not be too surprising.

The thing is that you might theoretically device a [dependent type system](http://en.wikipedia.org/wiki/Dependent_type) that covers such links between the structure of one data type and the value of another expression -- it is just a bit complicated and it would feel very unusual for someone used to imperative languages. But hey, it is for a compiler IR. This is what i was referring to. 

But I think we do not need this complexity. If we encode it in our IR using the `array<..>` type it is just  forcing us to store the dimensions with the array as well as a pointer to the data block, e.g. by utilizing a variable sized struct of the form
```C
struct int3d {
   unsigned s1, s2, s3;
   int data[];
}
```
and use those dimensions as offsets whenever conducting an access in the generated code. So 
```C
a[x][y][z]
```
becomes 
```C
a.data[x*a.s2*a.s3+y*a.s3+z]
```
Note that `s1` is required e.g. for implementing the `sizeof` operator properly. This way we are free to pass around array references to arbitrary functions and do not have to impose all those restrictions C99 has. And essentially that's the same that C99 does, we only move the storage space for the sizes from the stack to the location the data is stored. And if the backend discovers that an multidimensional array is not escaping a local scope we can always fall back to the C99 VLAs as an optmization -- in case this actually makes a performance difference.

**Comment by HerbertJordan** [comment]
Some responses to previous comments:

@0ife In INSPIRE the roles of arrays and references are clearly separated. Arrays organize the internal structure of a value while references provide mutable memory states. Those can -- and I strongly suggest that they should -- be separated. In our analysis and the IR encoding we utilize data-paths as replacements for pointer arithmetic. Essentially they are equivalent, however, with data paths we can model accesses without bothering with the low-level implementation details like word-widths of data types, padding, alignment, address spaces, or the convertibility of pointers to integers and vica versa. I guess for a high-level IR this type-save approach is more adequate. It also should reduce the complexity of the resulting constraints within analysis by utilizing available structural information to prune e.g. alias analysis more effectively (if you are interested, all that stuff is written up in the thesis).

@LuisAyuso Note that the type `array<array<int,1>,1>` and `array<int,2>` are semantically different. While in the first case each row may have a different length, the second one is forced to have a rectangular shape. Also, the first can be accessed utilizing a single subscript to obtain an array which can be accessed by a consecutive subscript operator application. However, in the 2-d case you can only access a field providing two indices. Providing only one index is not a valid operation.

**Comment by LuisAyuso** [comment]
I undestand, 
Somehow i was thinking on some unified system (using nested types) that allow two features:
- addressing ranges of the multidimensional array by providing a number a subscripts smaller than the number of dimensions (which is not such an alien operation)
- utilizing similar or the same expressions to subscript both  manual constructed ND-arrays (heap) and variable-sized-arrays (stack). This would avoid the need to write code that distinguish the cases in the analysis (@0ife ).
On the other hand, i like the idea to store the dimensions somewhere as they turn useful later on. 
maybe the array type could hold one single size value as you wrote and can be nested to stack dimensions. 

Another issue to consider is the interaction array-vector. You can write something like:
`int a[n][10]`  where one of the dimensions is known at compile time

**Comment by HerbertJordan** [comment]
Right,

- Regarding the sub-ranges: in our first IR draft we had stuff like this. A left-over is the (most likely nowhere implemented) `array.ref.projection` operator
https://github.com/insieme/insieme/blob/master/code/core/include/insieme/core/lang/inspire_api/basic.def#L514
We should review those operators regarding the new capabilities of GCC introducted by the Cilk extension (Array Notation) -- since those make it easy for us to support them efficiently in the backend.

- Indeed, being capable of handling e.g. 2d array created utilizing static dimensions on the stack, on the heap or dynamic dimensions on the stack or the heap as well as 2d arrays with index vectors on the heap utilizing the same IR constructs would be very nice for conducting analysis. I am pretty sure that for all those the necessary IR constructs are available -- and it comes down to proper frontend support. And, to some degree, to the willingness to diverge from the implementation details specified by the user. If a user defines a 2D vector with index vectors we should be brave enough to ignore those details and just use a 2D array. But this requires frontend work + IR analysis.

- Mixed array-vector operations are pretty clear how to handle I guess. We just have to make up our minds on what we want. Your example `int a[n][10]` could be encoded using an `array<vector<int,10>,1>` or an `array<int,2>` or `array<array<int,1>,1>`. I'd say that a nice regulation would be that we turn as many trailing static indices as possible into vectors and do the rest as n-dimensional arrays. Hence, `int a[n][m][20]` becomes `array<vector<int,20>,2>` and `int a[n][20][m]` becomes a `array<int,3>`. It is in fact a matter a picking a solution from a set of options in a design space. Ideally this kind of policy is configurable.

**Comment by LuisAyuso** [comment]
- Regarding cilk, I dont think clang can parse the [:] syntax, so you can already forget about that.
So, I don't see the conclusion of all this talk, shall we continue with the current types and derived operators?  introduce a bunch of new ones for the missing features? and so?

**Comment by HerbertJordan** [comment]
To sum it up: I think we have everything it needs to simulate C99 and C++ code. 

The following steps should be conducted:
- throw out the distinction of array.1D and ND constructs => drop the 1D constructs and the ND extension
- clean up the available array operators
- add support for higher-dimensional array to the backend
- encode C99/C++ arrays in the frontend properly

**Comment by HerbertJordan** [comment]
Can you check about the [:] syntax? Maybe it is an upcoming features?

**Comment by LuisAyuso** [comment]
(cilk: I will do check it out)

I understand your plan, is clear and makes sense. Still though I have some concerns. My aim is to unify the typing and expressions related to arrays to a point which is coherent and axiomatic.
The same way Ref type unifies memory declared in stack/heap, arrays should implement everything that looks like an array using one single type (just to be coherent with the IR design). Then use a minimum set of operations. As @HerbertJordan pointed out, Array subscript is just syntactic sugar over pointer arithmetic, so we only need to model this, and just this behaviour correctly to support all C pointer array issues.  (@0ife, I say C, because Insieme compiles C. If anyone comes with a new frontend, is up to them to transpose and translate the stuff in the right way) 

-First: I don't find the need for vector types in the way we use them now. An array with a constant known size is just a case of a general array type. If the aim is (only) to facilitate the analysis of array operations, It is effetely insufficient:
`int a[10];` `f(a);`  where f is: `void f(int *param)....` The vector turns into array and the implicit size information is lost. This needs of an smarter analysis, which btw, we should already have. (CBA arithmetic?). This is a case of overspecialization.
Is there any other reason why an array of constant size vector should be a different type? I can not find any reason for this in @HerbertJordan Thesis. 
-Second: The Dimension in the array type is not needed if using type nesting. The ambiguity presented  for Array-Vector interaction (`array<vector<int,10>,1>` or `array<int,2>` `array<array<int,1>,1>`) may and will turn into problems: Having equivalent ways to model the same construct will turn into and unclear representation. It is not about choosing the right and appropriate representation, the problem is that when operating in an instance of this type, the expressions will produce types that might have any of the shown shapes. Detecting this and using the right operator just explodes the amount of exceptions and we will need to implement all kind of conversion derived operators. As @HerbertJordan explained before the use of nested of 2D arrays points out the differentiation between rectangular sized buffer and variable second dimension sizes, but, what is a rectangular sized array but a case in which all the second dimension sizes are equal? This, again, turns into overspecialization, and enforces differences between types which are not that different.

-What I propose:

 Unique Array Type, for const sized, variable sized and pointers. 
It should be something like:  `struct{ uint<8> : size, buffer<'a> : collection }` 
The buffer is nothing but a 1 dimensional array as we use right now, and size holds the value of evaluating the size expression. For the case of a statically sized array, the evaluation should be rather easy, and this allows the transitive use of such value in other scopes.

Multiple dimensions: just nesting the thing. There will be no type difference whenever is a pointer to array, array of vectors (as we understand them right now) or stack allocated arrays.

Access, one (maybe two) operators: the subscript. Which always returns an reference (or value) of the inner type. NO vector to array, NO ND_array to 1D_array, no anything, no need.
Use the array_view operations for pointer arithmetic. (we could add the base address in the equation, perform real pointer arithmetic in derived operators, not just literals) 
Construction: a couple of derived operators should make the job.

Performance: the backend compiler will never know about this and will not produce anything else but a pointer type, when heap, or an N-dimensional when heap (using analogous mechanism as for the variables allocation, where the type of the produced C variable is dependent of the initialization expression) 

C | IR type | IR code
------------ | ------------- | --------
`int a[10]` | `ref<array<int>>` | `decl ref<array<int>> a = var( ND_ARRAY([10], type(int))`
`int *a = (int*)malloc (10*sizeof(int));` | `ref<array<int>>` | `decl ref<array<int>> a = new( ND_ARRAY([10], type(int))`
`int a[10][n]` | `ref<array<int>>` | `decl ref<array<array<int>>> a = var( ND_ARRAY([10, n], type(int))`
and 
```
int **a = (int**)malloc (10*sizeof(int*));
for (int i = 0 ... 10) 
    a[i] = (int*) malloc (....);
``` 
`ref<array<array<int>>`
```
decl ref<array<array<int>>> a = new( ND_ARRAY([10], type(array<int>))
for (i ...)
     a[i] = new( ND_ARRAY([n], type(int))
```

And, last but not least: Mixed:
```
int *a[10];
for (int i = 0 ... 10) 
    a[i] = (int*) malloc (....);
``` 
`ref<array<array<int>>`
```
decl ref<array<array<int>>> a = var( ND_ARRAY([10], type(array<int>))
for (i ...)
     a[i] = new( ND_ARRAY([n], type(int))
```
I guess that the convenience of my approach is obvious,  If not clear yet, just realize that the types for all the multidimensional arrays are the same and any access expression will have the same operator and the same return type no matter what example we work on. 

Now, What do we do with the vector type. The vector type is still important and needed. We just need to narrow a little the definition for such. It is a continuous collection of elements, with constant size, which can be copied (at least in the input code). 
This represents all the extended types which match a register allocation and can be treated like a built in type. Making this will facilitate the compatibility with most of the opencl stuff, and will allow us to remove the duplicity with mmx_vector_types. 

Now I would appreciate some sleep-about it time, Don't be in a hurry to reply, just think about it before.

**Comment by LuisAyuso** [comment]
About Cilk:
There is a fully operative clang version for Cilkplus:  https://cilkplus.github.io/#status
The problem is that since it was finished in 2013 and never merged into clang, it seems to be stuck with clang 3.4  https://www.cilkplus.org/download#cilk-plus-llvm
Make ourselves dependant on a non updated software does not look like a good decision to me.

**Comment by PeterTh** [comment]
Also think about sizeof() semantics and how to model that function. (Could of course be kept as blackbox in all cases, but this will limit analysis potential)

**Comment by PeterTh** [comment]
We have a new unified array representation, it is implemented in the current frontend and can model arbitrarily nested static and dynamically nested arrays.
