### ISSUE TITLE
Frontend has a dependency to the Backend

### ISSUE THREAD

**Issue by berhoeckner** [insieme/insieme#67]
The FE InstrumentationRegionExtension has a dependency on the BE RuntimeExtension (backend/runtime/runtime_extension**s**.h) which implements an IR Extension to interface the Runtime.

Probably best to split this up and move the IR Extension into the Core, to the rest of the IR Extensions.
If this is moved check (and probably remove) in the frontend/CMakeLists.txt the dependency of the insieme_frontend library onto the insieme_backend library.

**Comment by HerbertJordan** [comment]
I'd suggest to provide a backend-independent instrumentation API for Inspire that is then implemented (or ignored) by various backend implementations.

Yes, this is just a more or less fancy way of saying that the extension should be moved to the core and the backend should support it ... and cleaning up the corresponding source code documentation.

**Comment by LuisAyuso** [comment]
:+1:

**Comment by PeterTh** [comment]
Fixed with https://github.com/insieme/insieme/commit/c22aa66600744e1bcc1c2ac9ff01a216ff2409d3 and https://github.com/insieme/insieme/commit/e5dd2a788d536d38c35179e027dc935e83d6048a.

**Comment by klois** [comment]
The dependency is still there in the CMakeList.txt. The reason is the generation of c-code in the testcases https://github.com/insieme/insieme/blob/86b04f6d959417cefc4aa4d47f7da5ec0dfb8fec/code/frontend/test/extensions/frontend_extension_test.cc and https://github.com/insieme/insieme/blob/86b04f6d959417cefc4aa4d47f7da5ec0dfb8fec/code/frontend/test/extensions/significance_extension_test.cc. 
The Frontend testcases also  have dependencies to the driver, because many use the https://github.com/insieme/insieme/blob/86b04f6d959417cefc4aa4d47f7da5ec0dfb8fec/code/driver/include/insieme/driver/cmd/insiemecc_options.h. I'd be happy if we could find a way to also get rid of that.

**Comment by PeterTh** [comment]
If you look at the description of the issue by our dearly departed then you'll see it's fully resolved. What you want is something more than that :P
