### ISSUE TITLE
Integration unit tests fail when there is a preprocessing step needed

### ISSUE THREAD

**Issue by stefanmoosbrugger** [insieme/insieme#73]
There is the option to execute a preprocessing step before an integration test gets executed.
This is for example the case in all ocl integration tests. The preprocessing step here is to copy the libicl files to the working directory. 

Unfortunately in the "driver integration unit tests" that check if the frontend, backend, ... component works properly the tests will fail because the preprocessing step is not executed. The reason for this is that the config file is used to get the parameters (includes, input files, lib paths, ...) but the "integration test driver" is not invoked.

This is a design issue and we should rethink how we test the single components (frontend, backend, ...). Either we use integration tests or we use the unit tests or is there any other idea?!

**Comment by PeterTh** [comment]
Should be fixed by unifying the way integration test are run across the integration tester and integration unit tests.

**Comment by peterz-dps** [comment]
This has been fixed with commit 86b04f6d959417cefc4aa4d47f7da5ec0dfb8fec

The integration test driver now has two new options: --preprocessing and --postprocessing
When run with one of these options it will execute only the pre- or post-processing actions of the test cases respectively. These steps will never be executed otherwise.

So in order to prepare the environment to run all the integration tests (and of course now also the two integration unit tests which use the integration test settings) one has to run the integration_tests driver with the --preprocessing option beforehand to prepare the environment. This will then e.g. cause the OpenCL library to be compiled and put into the correct location for the tests to run correctly.

Our hudson jobs also run the --postprocessing step after all tests have been executed in order to clean up. This actually might not be necessary on your local development machines, as at the moment the few .so files shouldn't really bother you. Later on when we have different preprocessing steps which might download/extract huge input files or so one might consider cleaning up after test runs also.

Also you will probably not need to run the preprocessing step before every test run. Running this step once now for every OpenCL setup and then every time a new test which requires some preprocessing should actually suffice.

Note that the integration tests as well as the integration unit tests will run a new special "check_prerequisites" step for each test case in case such a step is specified in the configuration file. This step can and should be used to make sure that the preprocessing has been done correctly. For an example how to use this stuff correctly take a look at the configuration file for the OpenCL test cases (https://github.com/insieme/insieme/blob/86b04f6d959417cefc4aa4d47f7da5ec0dfb8fec/test/ocl/config) and focus on the preprocessing, postprocessing and also the check_prerequisites entries in that file.
