### ISSUE TITLE
Type instantiation and variable renaming vs. recognition of derived builtins in the backend

### ISSUE THREAD

**Issue by PeterTh** [insieme/insieme#76]
When types are instantiated (or variables renamed, for that matter) the resulting construct no longer gets recognized by the backend as that specific builtin.

E.g. the builtin `bla('a v0) { return v0; }` will not be recognized for `bla(bool v0) { return v0; }` or `bla('a v1)  { return v1; }` or even `bla('b v0) { return v0; }`.

The question is whether the backend should attempt some kind of unification, or whether we should keep it as-is and attempt to minimize the risk of core utilities and transformations changing the builtins in any way.

A third option to consider is to not make the implementation of derived constructs visible at all to most code outside analyses.

**Comment by LuisAyuso** [comment]
I was considering another option: 
The derived operators might not have direct implementation in C because they are modelling the semantics of C operations. Therefore they should not be altered because they might be no longer reproducible by the backend.
The derived operators are there to provide the analysis framework with the means to understand the semantics of the program, i.e. data flow. But their implementation should not be altered.  For this reason I was considering to provide only Literal operators to be used by the frontend-backend, Those operators name the semantics but do not incorporate an implementation.
At the time of running analysis, we could replace them with the complete implementation  which allows introspection. 

I guess that does not solve the problem completely, since the literals still can be replaced by the instantiated version and missed as well.

**Comment by HerbertJordan** [comment]
To some extend it is also intendet to happen that some derived operators may be transformed into specialized versions. As long as those operators are actually derived operators, this should always work. 

The problem comes when a generic built-in literal is modified by altering its type. Here, utilizing literals explusive in the frontend and backend would not resolve the problem since it would just replace one literal by another. This must be prevented by the applied transformations, thus the core utilities. 

One of the reasons of the problem is that the backend only utilizes object-identity to recognice operators. Thus, variable renaming (damn variable names!! :) ) can abviously lead to problems. Also the renaming of type variables or the unrolling of a recursive type. 

What I think should be done is to create a more powerful equality operation for code fragments utilized by the backend (not the == operator of the nodes) that is comparing the normalized version of a code fragment. Further, the normalizer should be extended to types as well, such that 
- type variable names are normalized, e.g. in the order 'a, 'b, 'c, ...
- recursive types are in the least-unrolled form

Any ideas for additional rules?

**Comment by PeterTh** [comment]
We now have a combination of annotations and rules on builtins which circumvents this issue, as well as some more powerful comparison/matching operations which could be used in the backend if necessary.
