### ISSUE TITLE
Backend problem when trying to convert qualified recursive methods

### ISSUE THREAD

**Issue by stefanmoosbrugger** [insieme/insieme#85]
There is a problem when converting (recursive) functions from IR into target code. As all of you know we have this nice ClassMetaInfo structure that stores additional information like virtual or const flags, ...

Now what happens is: the backend starts converting from the entry point and maybe finds a call to a member function. It gets a little bit more tricky now:

1) This will jump into this code part https://github.com/insieme/insieme/blob/master/code/backend/src/function_manager.cpp#L439-L459. In line 442 we try to get the LambdaInfo for this LambdaExpr. 

2) We call getInfo(...) -> resolve(...) -> resolveInternal(...) for the lambda. It is important to know that we have no information about the const flag (i think this can also happen for virtual but lets forget about this at the moment) because this information is stored in the ClassMetaInfo. To solve this lack of knowledge there is a check in https://github.com/insieme/insieme/blob/master/code/backend/src/function_manager.cpp#L639-L647 that checks if the lambda is a member function. If yes, we resolve the class type of the member function. In line 646 we see that call.

3)  This will again jump into getTypeInfo(...) -> resolveType(...) -> resolveInternal(...) -> resolveStructType(...). The resolveStructType tries to convert all member functions, ctors, ... 
We can see this for member functions in: https://github.com/insieme/insieme/blob/master/code/backend/src/type_manager.cpp#L830-L855

4) This will lead to a getInfo call for every single member function as you can see in line 842. So lets go back to the function_manager.cpp file. Like in step 2 we will end up in resolveInternal(...) but this time we call resolveLambda(...) (see here https://github.com/insieme/insieme/blob/master/code/backend/src/function_manager.cpp#L663). This resolveLambda call converts the lambda definition. 

5) Ok, we are almost there. The resolveLambda calls resolveLambdaDefinition(...). The block in https://github.com/insieme/insieme/blob/master/code/backend/src/function_manager.cpp#L959-L1059 is executed. There you can see a block https://github.com/insieme/insieme/blob/master/code/backend/src/function_manager.cpp#L1004-L1009 that prevents that the LambdaInfo is inserted multiple times in the function info map. In our case there is no entry at the moment. But when we have a LambdaExpr x that calls some LambdaExpr y that calls x again (or any other recursive method) we will see that the unqualified LambdaInfo of x is the first entry in the function info map and the qualified LambdaInfo for x is thrown away.

How should we solve this issue? 
Upgrading the qualification is ugly and does not work. I don't know why yet.

**Comment by stefanmoosbrugger** [comment]
Ok, the only thing we can do here is: Whenever we call
resolveLambdaDefinition(...) we have to check if there is a
metaInfo available for the specific object type. If yes, extract
the const and virtual information from the class meta info 
and do not rely on the isConst and isVirtual that is passed 
to the resolveLambdaDefinition function.

Again, our way is something like:
resolveLambdaDefinition to a memberCall (lets call it X) 
is resolving everything that is used in the body of X. 
If we call a member function of a different type in the body
of X, the backend will resolve the whole type (including
all member functions, ctors, dtor, etc.) before continuing
with the next statement in the body of X. 

This is bad because it can happen that a member function 
of the other type (lets call this one Y) calls our X function 
and if this happens we have no virtual and const information
when X gets resolved the second time. X will be added to 
the function info store with const and virtual set to false and
whenever we come out of the first call of resolve X we will
not add it again because it is already there. baam... without const 
and virtual...

The resolve path looks like this (c -> const flag, v -> virtual flag):
```
resolve X c=1 v=0
     resolve Y ...
     add Y to functionInfoStore

     resolve anotherMemberOfObjectTypeOfY ...
     add anotherMemberOfObjectTypeOfY to functionInfoStore

     resolve anotherMemberOfObjectTypeOfY1 ...
     add anotherMemberOfObjectTypeOfY1 to functionInfoStore

     resolve anotherMemberOfObjectTypeOfY2 ...
          resolve X c=0 v=0
          add X to functionInfoStore
     add anotherMemberOfObjectTypeOfY2 to functionInfoStore

     etc....

do NOT add X again, because we have it already
```

Any ideas how this can be fixed in a better way? I guess it is not 
that easy without doing major backend modifications.

**Comment by PeterTh** [comment]
Generally, I think there should really only be one way to determine const/virtual/etc information, either always by metainfo or by argument.

**Comment by HerbertJordan** [comment]
I guess my suggestion in #61 should work here as well. We should add the const-modifiere to the type of the member function by accepting a `src<T>` instead of a `ref<T>`. Then we can drop the recording of this information in the MetaInfo object. (by the way, did you notice that the isses #60 and #61 are named nearly identical..)

I will have to think how to incorporate the virtual part as well into the function type.

**Comment by HerbertJordan** [comment]
One idea for getting the virtual part into the function type is by adding a new kind of function. We have `->` for plain functions, `=>` for closures and we could add `~>` for virtual functions, indicating that the call may be object dependent and re-directed. 

This would take another competence away from the MetaInfo thingy to the actual IR structure.
(this thinking makes me wonna work on the compiler again :) )

**Comment by HerbertJordan** [comment]
The thing about the `~>` introducing expression is that it would essentially have to model the following criteria:
 - it has to assign to its target type a unique lambda; nowhere in the program an alternative implementation must be located
 - it must group the overloads of various types together such that it is possible to know what function actually is overloaded (since they do not have a name .. ah, everything is so easiy in nominal IRs)
 - it has to be capable of expressing pure virtual functions
 - it has to offere means for interfacing with external libraries / definitions

One suggestions would be an expression construct like the following:
`dispatch { lamda1, lambda2, ... , lambdaN }`
where the included lambda expressions are the overloads. They must all be member-functions and have compatible types (co-variant return types, contra-variant arguments), their object type must be consistently a `ref` or a `src` and no two implementations must have the same object type. Furthermore, the object types have to be in an corresponding inheritance relation (so, if B is a subtype of A, then overloads for A and B can be included; if A and B are unrelated, the expression is not a valid expression => semantical error).

The type of the `dispatch` expression would be the common base type of all the lambdas (smallest object type, smallest argument type, widest result type) with a `~>` instead of a `->`. And it can be utilized in an arbitrary call expression.

The backend would pick a name for each dispatch expression (probably inspired by a name annotation) and place declarations and definitions into all involved types -- including necessary pure virtual declarations.

How does this sound?

**Comment by PeterTh** [comment]
I really like the `src<T>` idea for const members. It directly models the semantics without introducing new constructs and should be simple to implement. *However*, what about `mutable`? In our semantics we couldn't write to a `mutable` member in a `const` method.

**Comment by PeterTh** [comment]
There are a few ways of going about solving this
* Keeping `src<>` semantics "clean", that is, having them only refer to truly constant references. However, this means that there is no way to map C/C++ `const` to `src<>`, rendering it basically useless for those input languages.
* Introducing a third reference type, let's call it `mut<>`. It's `const` at the C/C++ level but actually equivalent to `ref<>` from an IR/analysis PoV, except for dispatch resolve purposes.
* Implementing `const` as `src<>`, and access to mutables with casts. This sounds terrible, but ...

Thinking about it, `const_cast`s present the exact same issue as `mutable` does. Therefore, we can at least reduce this to a single point of failure by handling it the same, and the only way which works is casts.

**Comment by HerbertJordan** [comment]
I'd as well go for the cast and treat accesses to mutables as implicit const-casts. 

Any idea of other consequences of `mutable` modifiers except for saving the user from writting const casts?

**Comment by HerbertJordan** [comment]
The nice thing about a value of type `src<T>` in this context is that it garangees that there is a actual memory location that just can not be modified since there is no matching operator -- in contrast to a value of type `T` where there is no memory location in the IR semantic and probably also not in the resulting C program.

**Comment by PeterTh** [comment]
Yeah, I agree that handling ´mutable´ as implicit casts at each site of use makes the most sense.

**Comment by PeterTh** [comment]
There is no metainfo in inspire 2.0.

As such, this problem is implicitly resolved.
