### ISSUE TITLE
Return type instantiation

### ISSUE THREAD

**Issue by PeterTh** [insieme/insieme#94]
Return types are not instantiated even when they could be.

E.g. instantiating

	lambda ('a arg) -> 'b {
		return arg;
	}(5)

results in 

	let fun000 = fun(int<4> v1) -> 'b {
	    return v1;
	};

rather than

	let fun000 = fun(int<4> v1) -> int<4> {
	    return v1;
	};

**Comment by HerbertJordan** [comment]
The type `('a)->'b` is not a valid IR type. I guess the corresponding semantic check is missing.

The lambda should have the type `'a -> 'a`

Background info: a generic IR type is only inhabited if the type, read as a implication, is a tautology. For instance, `'a -> 'a` seen as the propositional formula `a -> a` is a tautology; so would be `('a,'b)->'b` interpreted as `(a ∧ b) -> b`; however, `'a->'b` interpreted as `a -> b` is not a tautology.

Of cause this is not the real reason why no lambda can exist for those types, but it has been shown that propositional tautologies and inhabited types are the same. And this is a simple way to check whether a type is inhabited or not.

Somebody interrested in implementing this semantic check?

**Comment by PeterTh** [comment]
I was not aware of this limitation - I considered it like an auto return type. Anyway, https://github.com/insieme/insieme/commit/4cd39816171318ba4b399f8ac7e61ad6168c45c1 (implemented yesterday) makes it work like Stefan and I would expect, but we can remove that if it's detrimental behavior.

**Comment by HerbertJordan** [comment]
When I looked now into the implementation of the instantiator I am surprised how overloaded this actually simple utility is now. For instance, it allows you to chose to only instantiate type variables, type parameters or both and I have to wonder in which case someone might require any other option than the both? Also, regarding the skip lists. There should actually be only one way to instantiate a lambda for a call -- why would there be a need for the user to tell the instantiator how to do his job?

I guess the point is that many of those core signatures become more and more overloaded, sometimes with feature that are -- i think -- just needed to fix symptoms of issues that are not properly handled at their source. Maybe because they are to complex, maybe because we haven't identified them yet, or maybe because they would be (seemingly) too much work. 

The problem is, the more options you offer, the more complex it gets, the less likely it is covered by unit tests, and the more likely it is to produce errors -- both, within the core and as a user of the tools. And this will hamper productivity.

When I'm back I would like to spend a few days in consolidating the core, maybe in combination with the Inspire 1.5 upgrade #29.

**Comment by PeterTh** [comment]
The instantiator is actually pretty well unit tested, see instantiation_test.cc

As for why you need a skip list, that's because there are cases where you don't want to instantiate some signatures, e.g. if you are in the backend you don't want to instantiate operators which are handled generically in the operator table. And obviously the core utility shouldn't be aware of the backend operator table, so it needs to be a parameter.
